# Generated by Django 4.2 on 2025-09-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order',
            field=models.FloatField(default=0),
        ),
    ]
